CREATE TABLE images (
id SMALLINT auto_increment,
url VARCHAR(300) NOT NULL,
PRIMARY KEY (id)
);
CREATE TABLE users (
	id SMALLINT AUTO_INCREMENT,
	login VARCHAR(50) NOT NULL,
	password VARCHAR(50) NOT NULL,
	PRIMARY KEY (id)
);
CREATE TABLE comments (
	id SMALLINT AUTO_INCREMENT,
	text VARCHAR(1000) NOT NULL,
	id_image SMALLINT NOT NULL,
	id_user SMALLINT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (id_image) REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (id_user) REFERENCES images (id) ON DELETE CASCADE ON UPDATE CASCADE
);